export const technologies = [
	{ name: "5G", logo: "5g-logo" },
	{ name: "Linux", logo: "linux-logo" },
	{ name: "Kubernetes", logo: "kubernetes-logo" },
	{ name: "Docker", logo: "docker-logo" },
	{ name: "React - React Native", logo: "react-logo" },
	{ name: "Redux", logo: "redux-logo" },
	{ name: "Nextjs", logo: "nextjs-logo" },
	{ name: "Typescript", logo: "typescript-logo" },
	{ name: "Golang", logo: "golang-logo" },
	{ name: "Networking", logo: "network-logo" },
	//{ name: "Material UI", logo: "mui-logo" },
	//{ name: "Cypress", logo: "cypress" },
	{ name: "Tailwind", logo: "tailwind-logo" },
	//{ name: "GraphQL", logo: "graphql-logo" },
	//{ name: "React Testing Library", logo: "testing-library" },
	//{ name: "Babel", logo: "babel-logo" },
	//{ name: "Webpack", logo: "webpack-logo" },
	//{ name: "Firebase", logo: "firebase-logo" },
	{ name: "MongoDB", logo: "mongodb-logo" },
	// { name: "CSS", logo: "css-logo" },
	// { name: "HTML", logo: "html5-logo" },
	// { name: "Javascript", logo: "javascript-logo" },
];
