export const technologies = [
    { name: "React", logo: "react-logo" },
    { name: "Redux", logo: "redux-logo" },
    { name: "Nextjs", logo: "nextjs-logo" },
    { name: "Typescript", logo: "typescript-logo" },
    { name: "Material UI", logo: "mui-logo" },
    { name: "Cypress", logo: "cypress" },
    { name: "React Testing Library", logo: "testing-library" },
    { name: "Babel", logo: "babel-logo" },
    { name: "Webpack", logo: "webpack-logo" },
    { name: "Firebase", logo: "firebase-logo" },
    { name: "CSS", logo: "css-logo" },
    { name: "HTML", logo: "html5-logo" },
    { name: "Javascript", logo: "javascript-logo" },
];
