export const blogPosts = [
    {
        topic: "firebase",
        title: "Firebase-1",
        name: "firebase-1",
        logoName: "firebase-logo",
        createDate: "03 March 2022",
        key: "1",
    },
    {
        topic: "typescript",
        title: "useState hook with Typescript",
        name: "typescript-1",
        logoName: "typescript-logo",
        createDate: "04 March 2022",
        key: "2",
    },
    {
        topic: "typescript",
        title: "useEffect hook with Typescript",
        name: "typescript-2",
        logoName: "typescript-logo",
        createDate: "06 March 2022",
        key: "3",
    },
    {
        topic: "javascript",
        title: "Array methods of Javascript",
        name: "javascript-1",
        logoName: "javascript-logo",
        createDate: "07 March 2022",
        key: "4",
    },
    {
        topic: "react",
        title: "React Context and useContext() Hook",
        name: "useContext",
        logoName: "react-logo",
        createDate: "08 March 2022",
        key: "5",
    },
    {
        topic: "react",
        title: "Memoization and useMemo() Hook",
        name: "useMemo",
        logoName: "react-logo",
        createDate: "30 March 2022",
        key: "6",
    },
    {
        topic: "react",
        title: "React Custom Hooks",
        name: "customHooks",
        logoName: "react-logo",
        createDate: "11 April 2022",
        key: "7",
    },
    {
        topic: "redux",
        title: "Redux-Saga Implementation on React",
        name: "saga-1",
        logoName: "redux-logo",
        createDate: "22 April 2022",
        key: "8",
    },
    {
        topic: "javascript",
        title: "Read files in Javascript",
        name: "read-files-in-js",
        logoName: "javascript-logo",
        createDate: "10 May 2022",
        key: "9",
    },
     {
        topic: "react",
        title: "Dropping Image Files on React",
        name: "drop-image-react",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "10",
    },
    {
        topic: "react",
        title: "Controlled & Uncontrolled Components",
        name: "controlled-uncontrolled-input",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "11",
    },
    {
        topic: "react",
        title: "Code Splitting in React",
        name: "code-splitting",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "12",
    },
    {
        topic: "react",
        title: "Handling Errors in React",
        name: "error-handling",
        logoName: "react-logo",
        createDate: "16 May 2022",
        key: "13",
    },
];
