const blogPosts = [
    {
        topic: "firebase",
        title: "Firebase-1",
        name: "firebase-1",
        logoName: "firebase-logo",
        createDate: "03 March 2022",
        key: "1",
    },
    {
        topic: "typescript",
        title: "useState hook with Typescript",
        name: "typescript-1",
        logoName: "typescript-logo",
        createDate: "04 March 2022",
        key: "2",
    },
    {
        topic: "typescript",
        title: "useEffect hook with Typescript",
        name: "typescript-2",
        logoName: "typescript-logo",
        createDate: "06 March 2022",
        key: "3",
    },
    {
        topic: "javascript",
        title: "Array methods of Javascript",
        name: "javascript-1",
        logoName: "javascript-logo",
        createDate: "07 March 2022",
        key: "4",
    },
    {
        topic: "react",
        title: "React Context and useContext() Hook",
        name: "useContext",
        logoName: "react-logo",
        createDate: "08 March 2022",
        key: "5",
    },
    {
        topic: "react",
        title: "Memoization and useMemo() Hook",
        name: "useMemo",
        logoName: "react-logo",
        createDate: "30 March 2022",
        key: "6",
    },
    {
        topic: "react",
        title: "React Custom Hooks",
        name: "customHooks",
        logoName: "react-logo",
        createDate: "11 April 2022",
        key: "7",
    },
    {
        topic: "redux",
        title: "Redux-Saga Implementation on React",
        name: "saga-1",
        logoName: "redux-logo",
        createDate: "22 April 2022",
        key: "8",
    },
    {
        topic: "javascript",
        title: "Read files in Javascript",
        name: "read-files-in-js",
        logoName: "javascript-logo",
        createDate: "10 May 2022",
        key: "9",
    },
    {
        topic: "react",
        title: "Dropping Image Files on React",
        name: "drop-image-react",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "10",
    },
    {
        topic: "react",
        title: "Controlled & Uncontrolled Components",
        name: "controlled-uncontrolled-input",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "11",
    },
    {
        topic: "react",
        title: "Code Splitting in React",
        name: "code-splitting",
        logoName: "react-logo",
        createDate: "13 May 2022",
        key: "12",
    },
    {
        topic: "react",
        title: "Handling Errors in React",
        name: "error-handling",
        logoName: "react-logo",
        createDate: "16 May 2022",
        key: "13",
    },
    {
        topic: "accessibility",
        title: "Accessibility on Web and Common Practices",
        name: "webAccessibility",
        logoName: "accessibility-logo",
        createDate: "6 July 2022",
        key: "14",
    },
    {
        topic: "javascript",
        title: "Managing Axios",
        name: "axios-custom-config",
        logoName: "javascript-logo",
        createDate: "19 July 2022",
        key: "15",
    },
    {
        topic: "react",
        title: "React Portals",
        name: "react-portal",
        logoName: "react-logo",
        createDate: "05 August 2022",
        key: "16",
    },
    {
        topic: "javascript",
        title: "Types in Javascript",
        name: "javascript-types",
        logoName: "javascript-logo",
        createDate: "17 August 2022",
        key: "17",
    },
    {
        topic: "javascript",
        title: "Asynchronous Javascript and Promises",
        name: "asynchronous-js-and-promises",
        logoName: "javascript-logo",
        createDate: "25 August 2022",
        key: "18",
    },
    {
        topic: "javascript",
        title: "Generators in Javascript",
        name: "generators-in-js",
        logoName: "javascript-logo",
        createDate: "25 August 2022",
        key: "19",
    },
    {
        topic: "redux",
        title: "React with RTK Query",
        name: "creatingRTKReducer",
        logoName: "redux-logo",
        createDate: "31 May 2023",
        key: "20",
    },
    {
        topic: "redux",
        title: "RTK Query Mutation Operation",
        name: "mutationonRTK",
        logoName: "redux-logo",
        createDate: "01 June 2023",
        key: "21",
    },
    {
        topic: "redux",
        title: "Caching Mechanism on RTK Query",
        name: "cachingOnRTKQuery",
        logoName: "redux-logo",
        createDate: "01 June 2023",
        key: "22",
    },
    {
        topic: "graphql",
        title: "GraphQL - Introduction and Installation",
        name: "introduction-installation",
        logoName: "graphql-logo",
        createDate: "31 July 2023",
        key: "23",
    },
    {
        topic: "graphql",
        title: "GraphQL - Schema Definition and Integration",
        name: "schema-definitions",
        logoName: "graphql-logo",
        createDate: "31 July 2023",
        key: "24",
    },
    {
        topic: "graphql",
        title: "GraphQL - Dealing with Dynamic Data",
        name: "dealing-with-dynamic-data",
        logoName: "graphql-logo",
        createDate: "04 August 2023",
        key: "25",
    },
    {
        topic: "graphql",
        title: "GraphQL - Adding More Types and Cross Relations",
        name: "adding-more-types-and-cross-relations",
        logoName: "graphql-logo",
        createDate: "04 August 2023",
        key: "26",
    },
    {
        topic: "graphql",
        title: "GraphQL - Tips on Query Writing",
        name: "tips-on-query-writing",
        logoName: "graphql-logo",
        createDate: "04 August 2023",
        key: "27",
    },
    {
        topic: "react",
        title: "Creating React Project From Scratch",
        name: "react-from-scratch",
        logoName: "react-logo",
        createDate: "10 August 2023",
        key: "28",
    },
];

export default blogPosts.reverse();
