import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Blog.module.scss";

import Layout from "../components/layout/layout";

import Background from "../public/blogBackground.jpg";
import { Typography, Grid, Button } from "@mui/material";

import { blogTechnologies } from "../public/logo";
import { blogPosts } from "../blog";
import { useRouter } from "next/router";

const Home = () => {
    const [topic, setTopic] = useState("");
    const router = useRouter();
    const gridStyle = {
        backgroundImage: `linear-gradient(180deg, rgba(3,1,22,0.7287289915966386) 0%, rgba(61,61,113,0.7371323529411764) 17%, rgba(255,255,255,1) 100%), url(${Background.src})`,
        backgroundSize: "cover",
    };

    const filteredPosts = () => {
        if (topic != "") {
            return blogPosts.filter((el) => el.topic === topic);
        }
        return blogPosts;
    };

    return (
        <div className={styles.container}>
            <Layout>
                <Head>
                    <title>Blog - erolyagizaydin</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main} style={gridStyle}>
                    <Typography className={styles.title} variant="h3">
                        Blog
                    </Typography>
                    <Typography className={styles.subtitle} variant="h5">
                        You can find my blog posts here. I like writing while
                        learning new stuff!
                    </Typography>
                    <Grid container className={styles.blogContainer}>
                        <Grid item xs={12} md={4} className={styles.grid}>
                            <Typography
                                variant="h6"
                                className={styles.blogTitle}
                            >
                                Topics
                            </Typography>
                            {blogTechnologies.map((el) => (
                                <Grid
                                    item
                                    xs={12}
                                    className={styles.logoGrid}
                                    key={el.key}
                                    onClick={() => setTopic(el.key)}
                                >
                                    <Image
                                        src={
                                            require(`../public/logo/${el.logo}.svg`)
                                                .default
                                        }
                                        alt={`${el.logo}`}
                                        height={40}
                                        width={40}
                                        className={styles.logoImage}
                                    />
                                    <Typography
                                        variant="h6"
                                        className={styles.logoText}
                                    >
                                        {el.name}
                                    </Typography>
                                </Grid>
                            ))}
                        </Grid>
                        <Grid item xs={12} md={7} className={styles.grid}>
                            <Typography
                                variant="h6"
                                className={styles.blogTitle}
                            >
                                Posts
                            </Typography>
                            {filteredPosts().map(
                                ({ title, logoName, createDate, key }) => (
                                    <Grid
                                        item
                                        xs={12}
                                        key={title}
                                        className={styles.logoGrid}
                                    >
                                        <Image
                                            src={
                                                require(`../public/logo/${logoName}.svg`)
                                                    .default
                                            }
                                            alt={`${logoName}`}
                                            height={40}
                                            width={40}
                                            style={{ flex: 1 }}
                                        />
                                        <Typography
                                            variant="h6"
                                            className={styles.logoText}
                                            style={{ flex: 2 }}
                                        >
                                            {title}
                                        </Typography>
                                        <Typography
                                            variant="subtitle2"
                                            className={styles.logoText}
                                            style={{ flex: 1 }}
                                        >
                                            {createDate}
                                        </Typography>
                                    </Grid>
                                )
                            )}
                        </Grid>
                    </Grid>
                    <Grid item xs={12} className={styles.buttonGrid}>
                        <Button
                            variant="outlined"
                            onClick={() => router.push("/")}
                        >
                            Back to Home
                        </Button>
                    </Grid>
                </main>
            </Layout>
        </div>
    );
};

export default Home;
