import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Layout from "../components/layout/layout";
import LandingImage from "../components/landingImage/landingImage";
import ServicesGrid from "../components/servicesGrid/servicesGrid";
import TechGrid from "../components/techGrid/techGrid";
import ProjectsStack from "../components/projectsStack/projectsStack";
import ContactGrid from "../components/contactGrid/contactGrid";

const Home = () => {
    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>erolyagizaydin</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <LandingImage />
                    <ServicesGrid />
                    <TechGrid />
                    <ProjectsStack />
                    <ContactGrid />
                </main>
            </div>
        </Layout>
    );
};

export default Home;
